name: malioboromall
description: Malioboro Mall Shop & Deals
version: 1.1.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.2.1
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.5
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  flutter_launcher_icons: ^0.8.0
  flutter_open_whatsapp: ^0.1.2
  flutter_statusbarcolor: ^0.2.3
  fluttertoast: ^7.0.4
  google_fonts: ^1.1.1
  grouped_list: ^3.5.0
  http: ^0.12.2
  localstorage: ^3.0.2+5
  page_transition: ^1.1.6
  path_provider: ^1.6.10
  salomon_bottom_bar: ^2.0.0
  scoped_model: ^1.0.1
  sqflite: ^1.3.1
  url_launcher: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: assets/icon/coklat.png

flutter:
  assets:
    - assets/
    - assets/icon/

  uses-material-design: true
