name: malioboromall
description: Malioboro Mall Yogyakarta Shopping App
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.2.1
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.5
  ff_navigation_bar: ^0.1.5
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  flutter_launcher_icons: ^0.8.0
  flutter_statusbarcolor: ^0.2.3
  fluttertoast: ^7.0.4
  http: ^0.12.2
  localstorage: ^3.0.2+5
  path_provider: ^1.6.10
  scoped_model: ^1.0.1
  sqflite: ^1.3.1
  url_launcher: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: assets/icon/coklat.png

flutter:
  assets:
    - assets/icon/

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Italic.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Thin.ttf
